### ISSUE TITLE
Unable to use with Remix Run

### ISSUE THREAD

**Issue by jdaly13** [TxnLab/use-wallet#12]
First Off I wanted to thank for at least attempting to build out this library - It's something the Algorand ecosystem desperately needs.

However currently while using remix.run the plugin in unusable with many errors - remix uses Esbuild.
I kept getting build errors that I needed to install dependencies which are marked as peer dependencies in your app
algorand-walletconnect-qrcode-modal and @blockshake/defly-connect even when I install those 
I keep getting process is undefined when importing anything from your package in the browser leaving my application unusable.
`const NODE_SERVER = process.env.NODE_SERVER ||` line 14
I tried to set the environment variable but to no avail it breaks no matter what

Also I cloned your repo and in order to run the storybooks - I needed to install webpack as well
Let me know if I can help out in anyway - I think it's a great project to have and hope it becomes the "raindbowkit or web3modla" of algorand.

**Comment by jdaly13** [comment]
see this comment  on the issue - essentially you would need to use CRA or NextJS to use your plugin - I'm hoping you support more than these two 

https://github.com/remix-run/remix/issues/1186#issuecomment-999190424

**Comment by gabrielkuettel** [comment]
I've only tested this with React and NextJS (and built it with those in mind), but I will take a look at this, and see if we can patch it to be compatible with Remix Run. 👍

**Comment by gabrielkuettel** [comment]
`use-wallet` V1 works with Remix now. I set up an example application here: https://github.com/gabrielkuettel/use-wallet-remix-example

Since Remix doesn't support dynamic imports, you'll need to setup the providers differently and provide static imports of the provider dependencies and `algosdk`. See [Provider Configuration](https://github.com/TxnLab/use-wallet#provider-configuration) for more details. 

Note: there's still an issue with hydration that affects SSR frameworks. It shouldn't affect functionality but we'll patch that shortly. 

Let us know if this solves the issue for you!

**Comment by gabrielkuettel** [comment]
Hydration errors have been fixed as of `1.0.4`. https://github.com/TxnLab/use-wallet/releases/tag/v1.0.4

**Comment by gabrielkuettel** [comment]
I'm closing this for now. If you find that this didn't fix the issue, I will reopen it.
