### ISSUE TITLE
Transactions issued twice

### ISSUE THREAD

**Issue by siim0n** [TxnLab/use-wallet#130]
Hi, I noticed that on mobile, some users get double transactions, therefore get an overspend error sometimes, and it throws an error. How can I get some logs about that ?

**Comment by drichar** [comment]
This does not appear to be an issue with the use-wallet library, as it has been reported on dapps that do not use it. I suspect it is a WalletConnect v1 issue since that seems to be the common thread.

I'll continue to investigate and will reopen this issue if it looks like there's anything that can be done in the library to mitigate it.
