### ISSUE TITLE
WalletConnect client does not properly handle signed transactions that do not originate from the group sender

### ISSUE THREAD

**Issue by PhilGabardo** [TxnLab/use-wallet#44]
My use case involves leveraging a hot wallet to sign some transactions in a group. The sender needs to sign some other transactions, but the group cannot be signed when using the WalletConnect client. Note - it does work when using the Pera client.

**Comment by gabrielkuettel** [comment]
Can you show a sample transaction and how you're signing it?

**Comment by PhilGabardo** [comment]
Do you mean signing the transaction with the  hot wallet? Or signing the transaction group with the SDK?

**Comment by gabrielkuettel** [comment]
> Do you mean signing the transaction with the hot wallet? Or signing the transaction group with the SDK?

Sorry for the late response here. Any code where you're using `use-wallet` API that is failing would be helpful. Thanks!

**Comment by algolog** [comment]
I confirm the issue. Shouldn't we push DecodedSignedTransaction object here?

https://github.com/TxnLab/use-wallet/blob/cbbfefb51d59eddcfb4f5388675e58b906cb27f5/src/clients/walletconnect/client.ts#L243

**Comment by drichar** [comment]
@algolog The transactions returned do need to be encoded, but there's a bug in the reduce function creating that array.

By iterating over the payload from WalletConnect instead of the original transaction group, the first condition will always evaluate to `true` and all transactions are treated as signed transactions. This will be fixed in the next release.

**Comment by drichar** [comment]
This is fixed in https://github.com/TxnLab/use-wallet/releases/tag/v1.2.6

**Comment by PhilGabardo** [comment]
Thank you!
